version: '3.8'

services:
  stremio-addon:
    build: .
    container_name: stremio-telegram-addon
    ports:
      - "8080:8080"
    environment:
      # Telegram API Credentials
      API_ID: ${API_ID}
      API_HASH: ${API_HASH}
      PHONE_NUMBER: ${PHONE_NUMBER}
      
      # Channels to monitor (comma-separated)
      MONITORED_CHANNELS: ${MONITORED_CHANNELS}
      
      # Server configuration
      HOST: 0.0.0.0
      PORT: 8080
      
      # Performance settings (adjust based on your VPS specs)
      CHUNK_SIZE: 1048576                    # 1MB chunks
      MAX_CACHE_SIZE: 5368709120             # 5GB cache
      CACHE_CLEANUP_INTERVAL: 3600           # 1 hour
      MAX_CONCURRENT_DOWNLOADS: 3            # Concurrent streams
      RATE_LIMIT_DELAY: 1.0                  # Delay between operations
      
      # Addon details
      ADDON_NAME: "Personal Telegram Media"
      ADDON_VERSION: "1.0.0"
      
    volumes:
      # Persistent storage for session, cache, and database
      - ./data/sessions:/app/sessions
      - ./data/cache:/app/cache
      - ./data/database:/app/data
      
    restart: unless-stopped
    
    # Keep container alive and prevent idle shutdown
    tty: true
    stdin_open: true
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    
    # Resource limits (adjust based on your VPS specs)
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '0.5'

volumes:
  sessions:
  cache:
  database:
